name: TADevelops
description: TechnologyAdvice Developer Blog
meta_description: "Blog about JavaScript, Node, Docker, React, and much more!"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'http://technologyadvice.github.io'
google_analytics: 'UA-40219271-4'
permalink: /:title/

# Details for the RSS feed generator
url:            'http://technologyadvice.github.io'
author:         'TechnologyAdvice'

gems: [jekyll-paginate]

authors:
  tom.shawver:
    pic: tom.shawver.jpg
    name: Tom Shawver
    email: tom.shawver@technologyadvice.com
    bio: |
      Tom is the CTO of TA, with specializations in architecture, infrastructure,
      and security. His passions involve building a culture of experimentation and
      open-source dedication, products that make technology choices easier, and
      author biographies written in the third person.
  kent.safranski:
    pic: kent.safranski.jpg
    name: Kent Safranski
    email: kent.safranski@technologyadvice.com
    bio: |
      Kent is an architect at TA and heavily involved in the team's work with
      Node.js, Docker, infrastructure and services. He is passionate about
      clean, modular development and workflow automation.
  levi.thomason:
    pic: levi.thomason.jpg
    name: Levi Thomason
    email: levi.thomason@technologyadvice.com
    bio: |
      Levi is a Senior Software Engineer at TA who really wants to blog but is 
      extremely busy. We know he will soon.
  peter.svetlichny:
    pic: peter.svetlichny.jpg
    name: Peter Svetlichny
    display_name: Peter
    email: peter.svetlichny@technologyadvice.com
    bio: |
      Peter is a Software Engineer on the backend at TA, with a background in
      music and creative writing. He's interested in modular development,
      Docker, and all things Node.js.
  thomas.vaughn:
    pic: thomas.vaughn.jpg
    name: Thomas Vaughn
    email: thomas.vaughn@technologyadvice.com
    bio: |
      Thomas is a Senior Software Engineer at TA focused on backend work. He's a
      recovering PHP developer who is passionate about Node.js, the local tech
      community, ice hockey and bacon.
  david.zukowski:
    pic: david.zukowski.jpg
    name: David Zukowski
    email: david.zukowski@technologyadvice.com
    bio: |
      David is a Senior Software Engineer at TA focused on frontend work. He has
      a love for functional programming, ReactJS, and web application performance
      and optimization.
  josh.habdas:
    pic: josh.habdas.jpg
    name: Josh Habdas
    display_name: Josh
    email: josh.habdas@technologyadvice.com
    bio: |
      Josh is a former Senior Software Engineer at TA who focused on Web Platform work
      and also contributed to our open source tools. He's passionate about expressive
      code and minimalism.
