name: TADevelops
description: TechnologyAdvice Developer Blog
meta_description: "Blog about JavaScript, Node, Docker, React, and much more!"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'http://technologyadvice.github.io'
google_analytics: 'UA-XXXXXXXX-X'
permalink: pretty

# Details for the RSS feed generator
url:            'http://technologyadvice.github.io'
author:         'TechnologyAdvice'

gems: [jekyll-paginate]

authors:
  tom.shawver:
    pic: tom.shawver.jpg
    name: Tom Shawver
    email: tom.shawver@technologyadvice.com
    bio: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
      do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat.
  kent.safranski:
    pic: kent.safranski.jpg
    name: Kent Safranski
    email: kent.safranski@technologyadvice.com
    bio: |
      Kent is architect at TA and heavily involved in the team's work with
      Node.js, Docker, infrastructure and services. He is passionate about
      clean, modular development and workflow automation.
  levi.thomason:
    pic: levi.thomason.jpg
    name: Levi Thomason
    email: levi.thomason@technologyadvice.com
    bio: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
      do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat.
  josh.habdas:
    pic: josh.habdas.jpg
    name: Josh Habdas
    display_name: Josh
    email: josh.habdas@technologyadvice.com
    bio: |
      Josh is a Senior Software Engineer at TA focused on Web Platform work
      and helping build our open source tools. He's passionate about expressive
      code and minimalism. You can read more of Josh's tech articles on his
      personal tech blog at http://habd.as.
  peter.svetlichny:
    pic: peter.svetlichny.jpg
    name: Peter Svetlichny
    display_name: Peter
    email: peter.svetlichny@technologyadvice.com
    bio: |
      Peter is a Software Engineer on the backend at TA, with a background in music and creative writing. He's interested in modular development, Docker, and all things Node.js.

